### ISSUE TITLE
Unhandled exception right after logging in

### ISSUE THREAD

**Issue by RamyMahrous** [Dainius14/twinder#12]
at Twinder.ViewModel.MainViewModel.<GetRecs>d__126.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Twinder.ViewModel.MainViewModel.<FullConnect>d__123.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Twinder.ViewModel.MainViewModel.<StartInitialize>d__122.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Dainius14** [comment]
Is it the first time you log in?

**Comment by RamyMahrous** [comment]
By your app, Yes

**Comment by RamyMahrous** [comment]
I tried twice the same exception raises

**Comment by Dainius14** [comment]
Are you building from source or using latest version?

Try going to your local appdata folder, and deleting `Twinder` folder. Then launch app again
