### ISSUE TITLE
Lots of null reference errors on first load

### ISSUE THREAD

**Issue by mtlynch** [Dainius14/twinder#13]
I cleared my AppData\Local\Twinder folder, and rebuilt from 533fd47d93ca10b4383107fc5ee219a649b5bce1 but after I complete the FB auth flow, I get a bunch of null reference exceptions and can't run Twinder.

```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Twinder
  StackTrace:
       at Twinder.ViewModel.MatchListFilterViewModel.SortMatchList() in C:\tmp\twinder\ViewModel\MatchListFilterViewModel.cs:line 333
       at Twinder.ViewModel.MatchListFilterViewModel.set_SelectedSorting(SortingOptionsEnum value) in C:\tmp\twinder\ViewModel\MatchListFilterViewModel.cs:line 252
  InnerException: 
```

```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Twinder
  StackTrace:
       at Twinder.ViewModel.MatchListFilterViewModel.UpdateStatusBar() in C:\tmp\twinder\ViewModel\MatchListFilterViewModel.cs:line 522
       at Twinder.ViewModel.MatchListFilterViewModel.set_SelectedTab(TabItem value) in C:\tmp\twinder\ViewModel\MatchListFilterViewModel.cs:line 30
  InnerException: 
```

```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Twinder
  StackTrace:
       at Twinder.ViewModel.MatchListFilterViewModel.ApplyFilter(Object sender, FilterEventArgs e) in C:\tmp\twinder\ViewModel\MatchListFilterViewModel.cs:line 376
       at System.Windows.Data.CollectionViewSource.WrapFilter(Object item)
       at System.Windows.Data.CollectionViewSource.FilterStub.WrapFilter(Object item)
       at System.Windows.Data.ListCollectionView.PrepareLocalArray()
       at System.Windows.Data.ListCollectionView.RefreshOverride()
       at System.Windows.Data.CollectionView.RefreshInternal()
       at System.Windows.Data.CollectionView.Refresh()
       at System.Windows.Data.CollectionView.EndDefer()
       at System.Windows.Data.CollectionView.DeferHelper.Dispose()
       at System.Windows.Data.CollectionViewSource.ApplyPropertiesToView(ICollectionView view)
       at System.Windows.Data.CollectionViewSource.OnForwardedPropertyChanged()
       at System.Windows.Data.CollectionViewSource.add_Filter(FilterEventHandler value)
       at Twinder.ViewModel.MainViewModel.set_MatchList(ObservableCollection`1 value) in C:\tmp\twinder\ViewModel\MainViewModel.cs:line 46
       at Twinder.ViewModel.MainViewModel.<GetMatches>d__180.MoveNext() in C:\tmp\twinder\ViewModel\MainViewModel.cs:line 472
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Twinder.ViewModel.MainViewModel.<StartInitialize>d__178.MoveNext() in C:\tmp\twinder\ViewModel\MainViewModel.cs:line 339
  InnerException: 
```

```
Object reference not set to an instance of an object.
   at Twinder.ViewModel.MatchListFilterViewModel.ApplyFilter(Object sender, FilterEventArgs e) in C:\tmp\twinder\ViewModel\MatchListFilterViewModel.cs:line 376
   at System.Windows.Data.CollectionViewSource.WrapFilter(Object item)
   at System.Windows.Data.CollectionViewSource.FilterStub.WrapFilter(Object item)
   at System.Windows.Data.ListCollectionView.PrepareLocalArray()
   at System.Windows.Data.ListCollectionView.RefreshOverride()
   at System.Windows.Data.CollectionView.RefreshInternal()
   at System.Windows.Data.CollectionView.Refresh()
   at System.Windows.Data.CollectionView.EndDefer()
   at System.Windows.Data.CollectionView.DeferHelper.Dispose()
   at System.Windows.Data.CollectionViewSource.ApplyPropertiesToView(ICollectionView view)
   at System.Windows.Data.CollectionViewSource.OnForwardedPropertyChanged()
   at System.Windows.Data.CollectionViewSource.add_Filter(FilterEventHandler value)
   at Twinder.ViewModel.MainViewModel.set_MatchList(ObservableCollection`1 value) in C:\tmp\twinder\ViewModel\MainViewModel.cs:line 46
   at Twinder.ViewModel.MainViewModel.<GetMatches>d__180.MoveNext() in C:\tmp\twinder\ViewModel\MainViewModel.cs:line 472
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Twinder.ViewModel.MainViewModel.<StartInitialize>d__178.MoveNext() in C:\tmp\twinder\ViewModel\MainViewModel.cs:line 339
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Dainius14** [comment]
Could you try building now and check if this is fixed?

**Comment by mtlynch** [comment]
Yeah, still happening:

```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Twinder
  StackTrace:
       at Twinder.ViewModel.MatchListFilterViewModel.UpdateStatusBar() in C:\tmp\twinder\ViewModel\MatchListFilterViewModel.cs:line 522
       at Twinder.ViewModel.MatchListFilterViewModel.set_SelectedTab(TabItem value) in C:\tmp\twinder\ViewModel\MatchListFilterViewModel.cs:line 30
  InnerException: 
```

```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Twinder
  StackTrace:
       at Twinder.ViewModel.MatchListFilterViewModel.ApplyFilter(Object sender, FilterEventArgs e) in C:\tmp\twinder\ViewModel\MatchListFilterViewModel.cs:line 376
       at System.Windows.Data.CollectionViewSource.WrapFilter(Object item)
       at System.Windows.Data.CollectionViewSource.FilterStub.WrapFilter(Object item)
       at System.Windows.Data.ListCollectionView.PrepareLocalArray()
       at System.Windows.Data.ListCollectionView.RefreshOverride()
       at System.Windows.Data.CollectionView.RefreshInternal()
       at System.Windows.Data.CollectionView.Refresh()
       at System.Windows.Data.CollectionView.EndDefer()
       at System.Windows.Data.CollectionView.DeferHelper.Dispose()
       at System.Windows.Data.CollectionViewSource.ApplyPropertiesToView(ICollectionView view)
       at System.Windows.Data.CollectionViewSource.OnForwardedPropertyChanged()
       at System.Windows.Data.CollectionViewSource.add_Filter(FilterEventHandler value)
       at Twinder.ViewModel.MainViewModel.set_MatchList(ObservableCollection`1 value) in C:\tmp\twinder\ViewModel\MainViewModel.cs:line 46
       at Twinder.ViewModel.MainViewModel.<GetMatches>d__180.MoveNext() in C:\tmp\twinder\ViewModel\MainViewModel.cs:line 471
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Twinder.ViewModel.MainViewModel.<StartInitialize>d__178.MoveNext() in C:\tmp\twinder\ViewModel\MainViewModel.cs:line 338
  InnerException: 
```

```
Object reference not set to an instance of an object.
   at Twinder.ViewModel.MatchListFilterViewModel.ApplyFilter(Object sender, FilterEventArgs e) in C:\tmp\twinder\ViewModel\MatchListFilterViewModel.cs:line 376
   at System.Windows.Data.CollectionViewSource.WrapFilter(Object item)
   at System.Windows.Data.CollectionViewSource.FilterStub.WrapFilter(Object item)
   at System.Windows.Data.ListCollectionView.PrepareLocalArray()
   at System.Windows.Data.ListCollectionView.RefreshOverride()
   at System.Windows.Data.CollectionView.RefreshInternal()
   at System.Windows.Data.CollectionView.Refresh()
   at System.Windows.Data.CollectionView.EndDefer()
   at System.Windows.Data.CollectionView.DeferHelper.Dispose()
   at System.Windows.Data.CollectionViewSource.ApplyPropertiesToView(ICollectionView view)
   at System.Windows.Data.CollectionViewSource.OnForwardedPropertyChanged()
   at System.Windows.Data.CollectionViewSource.add_Filter(FilterEventHandler value)
   at Twinder.ViewModel.MainViewModel.set_MatchList(ObservableCollection`1 value) in C:\tmp\twinder\ViewModel\MainViewModel.cs:line 46
   at Twinder.ViewModel.MainViewModel.<GetMatches>d__180.MoveNext() in C:\tmp\twinder\ViewModel\MainViewModel.cs:line 471
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Twinder.ViewModel.MainViewModel.<StartInitialize>d__178.MoveNext() in C:\tmp\twinder\ViewModel\MainViewModel.cs:line 338
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
